### ISSUE TITLE
App doesnt open



### ISSUE THREAD

**Issue by niko-novice** [aritra-tech/Notify#267]
**Describe the bug**

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt;
	at z0.p0.<clinit>(SourceFile:1)
	at z0.p0.e(SourceFile:1)
	at k6.f.a(SourceFile:125)
	at k6.f.n0(SourceFile:29)
	at b2.b.n0(SourceFile:54)
	at b0.e.e(SourceFile:165)
	at b1.y.a(SourceFile:774)
	at b1.y.n0(SourceFile:102)
	at b2.b.n0(SourceFile:54)
	at c1.d0.b(SourceFile:440)
	at c1.d0.n0(SourceFile:82)
	at b2.b.n0(SourceFile:54)
	at v.d.d0(SourceFile:1)
	at t1.p.r(SourceFile:127)
	at t1.u.p(SourceFile:30)
	at t1.a2.a(SourceFile:26)
	at t1.k.a(SourceFile:5)
	at t1.u.c(SourceFile:1)
	at x2.g0.d(SourceFile:100)
	at x2.b0.F(SourceFile:174)
	at androidx.compose.material3.c8.u0(SourceFile:573)
	at x2.l0.h(SourceFile:33)
	at x2.c0.h(SourceFile:43)
	at b1.y0.b(SourceFile:184)
	at b1.y0.m(SourceFile:104)
	at androidx.compose.material3.q8.f(SourceFile:59)
	at d2.y.a(SourceFile:48)
	at d2.z.c(SourceFile:66)
	at z2.i1.a(SourceFile:1)
	at z2.i0.g(SourceFile:105)
	at z2.i0.E0(SourceFile:133)
	at z2.s.i0(SourceFile:18)
	at x2.x0.c(SourceFile:26)
	at z2.h0.m(SourceFile:15)
	at androidx.compose.material3.q8.f(SourceFile:59)
	at d2.y.a(SourceFile:48)
	at d2.z.c(SourceFile:66)
	at z2.i1.a(SourceFile:1)
	at z2.i0.F0(SourceFile:92)
	at z2.i0.i0(SourceFile:76)
	at x2.x0.c(SourceFile:26)
	at e1.q.b(SourceFile:44)
	at e1.n.u0(SourceFile:25)
	at x2.l0.h(SourceFile:33)
	at b1.y0.b(SourceFile:184)
	at b1.y0.m(SourceFile:104)
	at androidx.compose.material3.q8.f(SourceFile:59)
	at d2.y.a(SourceFile:48)
	at d2.z.c(SourceFile:66)
	at z2.i1.a(SourceFile:1)
	at z2.i0.g(SourceFile:105)
	at z2.i0.E0(SourceFile:133)
	at z2.s.i0(SourceFile:18)
	at x2.x0.g(SourceFile:41)
	at b1.t.c(SourceFile:293)
	at b1.t.u0(SourceFile:1379)
	at x2.l0.h(SourceFile:33)
	at z2.x.i0(SourceFile:38)
	at z2.h0.m(SourceFile:43)
	at androidx.compose.material3.q8.f(SourceFile:59)
	at d2.y.a(SourceFile:48)
	at d2.z.c(SourceFile:66)
	at z2.i1.a(SourceFile:1)
	at z2.i0.F0(SourceFile:92)
	at z2.i0.i0(SourceFile:76)
	at x2.x0.e(SourceFile:69)
	at x2.e0.a(SourceFile:12)
	at x2.e0.u0(SourceFile:19)
	at x2.l0.h(SourceFile:33)
	at b1.y0.b(SourceFile:184)
	at b1.y0.m(SourceFile:104)
	at androidx.compose.material3.q8.f(SourceFile:59)
	at d2.y.a(SourceFile:48)
	at d2.z.c(SourceFile:66)
	at z2.i1.a(SourceFile:1)
	at z2.i0.g(SourceFile:105)
	at z2.i0.E0(SourceFile:133)
	at z2.s.i0(SourceFile:18)
	at x2.x0.c(SourceFile:26)
	at z2.h0.m(SourceFile:15)
	at androidx.compose.material3.q8.f(SourceFile:59)
	at d2.y.a(SourceFile:48)
	at d2.z.c(SourceFile:66)
	at z2.i1.a(SourceFile:1)
	at z2.i0.F0(SourceFile:92)
	at z2.i0.i0(SourceFile:76)
	at x2.x0.d(SourceFile:66)
	at z2.n0.j(SourceFile:210)
	at z2.n0.f(SourceFile:127)
	at androidx.compose.ui.platform.AndroidComposeView.onLayout(Unknown Source:4)
	at android.view.View.layout(View.java:23033)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at androidx.compose.ui.platform.a.f(SourceFile:1)
	at androidx.compose.ui.platform.a.onLayout(Unknown Source:6)
	at android.view.View.layout(View.java:23033)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23033)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23033)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
	at android.view.View.layout(View.java:23033)
	at android.view.ViewGroup.layout(ViewGroup.java:6468)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3601)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3069)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2070)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8402)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
	at android.view.Choreographer.doFrame(Choreographer.java:813)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: androidx.compose.runtime.PrimitiveSnapshotStateKt
	... 125 more

**Comment by aritra-tech** [comment]
It's fixed in this latest release which is v1.8.1
