### ISSUE TITLE
The app crashes when trying to backup and there is a note with an image 

### ISSUE THREAD

**Issue by jamalnay** [aritra-tech/Notify#67]
I have created the first note with a simple text, then created a second note with text and an image of type **JPG**, when I tried to make a backup of the database the app crashes showing the following error in logcat

```
FATAL EXCEPTION: main
Process: com.aritra.notify, PID: 1841
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2180)
	at android.os.Parcel.writeParcelable(Parcel.java:2538)
	at android.os.Parcel.writeValue(Parcel.java:2439)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at androidx.compose.runtime.ParcelableSnapshotMutableState.writeToParcel(ParcelableSnapshotMutableState.kt:30)
	at android.os.Parcel.writeParcelable(Parcel.java:2538)
	at android.os.Parcel.writeValue(Parcel.java:2439)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeTypedObject(Parcel.java:2157)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1257)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

**Comment by logickoder** [comment]
Hey, I'm working on the backup functionality, so I would look into this

**Comment by logickoder** [comment]
@aritra-tech how do you propose we backup note images, we can try encoding the images to base 64 so we can save directly in the csv but that won't be clean

**Comment by aritra-tech** [comment]
That is the only option i.e. to encode the image to base 64. When I was working on this feature I tied a lot of things to back-up image but can't find the correct solution.

**Comment by logickoder** [comment]
The would mean we would have to compress the images to a certain point so as to reduce the encoded string

**Comment by logickoder** [comment]
My idea would have been to create a zip file containing the csv and the images, and in the csv, a column containing the names of the images so we can know how to restore the images correctly

**Comment by aritra-tech** [comment]
> My idea would have been to create a zip file containing the csv and the images, and in the csv, a column containing the names of the images so we can know how to restore the images correctly

Yeah we can do that.

**Comment by naitgacem** [comment]
I think what @logickoder is proposing makes more sense, as is common with all "Export your data" features of popular services.
